"""Fluent 设置界面的简体中文文案表

由 SettingsViewModelBase.translate() 在 ui.language == "zh-CN" 时查表使用。
"""

ZH_CN: dict[str, str] = {
    "ai_behavior": "AI 行为",
    "ai_processing": "AI 处理",
    "ai_provider": "AI 提供商",
    "api_key": "API 密钥",
    "api_key_optional": "API 密钥（可选）",
    "always_on_top": "始终置顶",
    "application": "应用",
    "apply": "应用",
    "audio_and_input": "音频和输入",
    "audio_device": "音频设备",
    "auto_detect_terminal": "自动检测终端应用",
    "auto_save_dragged_position": "自动保存拖动位置",
    "base_url": "基础 URL",
    "batch_reprocess": "批量重新处理",
    "revert_to_raw": "回退到原始转写",
    "chunk_duration": "分块时长",
    "clipboard_restore_delay_ms": "剪贴板恢复延迟 (ms)",
    "dashscope_default": "留空则使用 DashScope 默认地址",
    "audio_file": "音频文件",
    "close": "关闭",
    "copy_to_clipboard": "复制",
    "delete_record": "删除记录",
    "detail": "详情",
    "diagnostics": "诊断",
    "decision_reason": "决策原因",
    "enable_ai_streaming_output": "启用 AI 流式输出",
    "enable_ai_optimization": "启用 AI 文本优化",
    "enable_fallback": "启用备用输入方法",
    "enable_lexicon_review": "启用词汇候选审查",
    "enable_itn": "启用逆文本归一化",
    "enable_sentence_split": "启用句子切分",
    "fallback": "备用输入",
    "fallback_type": "备用类型",
    "fallback_reason": "备用原因",
    "final_text": "最终文本",
    "filter_thinking_tags": "过滤思考标签",
    "history": "历史",
    "hotkey_backend": "快捷键后端",
    "hotkeys": "快捷键",
    "active_hotkeys": "当前快捷键",
    "accept": "接受",
    "add_shortcut": "添加快捷键",
    "change": "更改",
    "capture_cancel_hint": "按 Esc 取消",
    "capture_duplicate_hotkey": "该快捷键已存在",
    "capture_failed": "无法开始录制，请重试",
    "capture_idle_hint": "点击添加或更改来录制新的快捷键组合",
    "capture_ready": "准备录制快捷键",
    "capture_timed_out": "录制超时，请重试",
    "capture_unavailable": "当前环境无法录制快捷键",
    "capturing_shortcut": "正在录制快捷键",
    "at_least_one_shortcut_required": "至少需要保留一个快捷键",
    "confirm": "确认",
    "edit_shortcut": "编辑快捷键",
    "edit_hotkeys": "编辑快捷键",
    "ignore": "忽略",
    "language": "语言",
    "launch_at_login": "Windows 登录时启动",
    "leave_empty_default": "留空则使用默认值",
    "load": "加载",
    "load_model_on_startup": "启动时加载模型",
    "log_level": "日志级别",
    "local_sherpa": "本地 sherpa-onnx",
    "max_log_file_size": "最大日志文件大小 (MB)",
    "max_retries": "最大重试次数",
    "memory_settings": "记忆设置",
    "duration": "时长",
    "evidence": "证据",
    "mode": "模式",
    "model": "模型",
    "model_id": "模型 ID",
    "no_hotkeys": "未配置快捷键",
    "no_lexicon_entries": "暂无本地词汇记忆",
    "no_review_suggestions": "暂无词汇候选",
    "streaming_mode": "流式模式",
    "no_history_records": "暂无历史记录",
    "openai_compatible": "OpenAI 兼容",
    "one_hotkey_per_line": "每行一个快捷键",
    "press_shortcut": "按下快捷键",
    "preferred_method": "首选方法",
    "preset_position": "预设位置",
    "provider": "提供商",
    "provider_credentials": "提供商凭据",
    "recording_overlay": "录音悬浮窗",
    "recording_details": "录音详情",
    "record_id": "记录 ID",
    "refresh": "刷新",
    "review_suggestions": "词汇候选",
    "review_run_completed": "词汇审查完成：{records} 条记录，{suggestions} 条候选",
    "review_run_running": "正在运行词汇审查...",
    "review_run_skipped": "词汇审查未运行：{reason}",
    "run_review_now": "运行词汇审查",
    "registered_hotkeys": "已注册快捷键",
    "remove": "移除",
    "remove_shortcut": "移除快捷键",
    "reject": "拒绝",
    "reprocess_of": "重处理来源",
    "revert": "还原",
    "retry": "重试",
    "search_history": "搜索转写或 AI 文本",
    "saved_vocabulary": "已保存词汇",
    "seconds": "秒",
    "selected_hotkey": "已选快捷键",
    "show_console_output": "显示控制台输出",
    "show_recording_overlay": "显示录音悬浮窗",
    "show_tray_notifications": "显示托盘通知",
    "start_minimized": "启动后最小化到托盘",
    "start_ai_after_first_chunk": "首个 ASR 分块完成后启动 AI",
    "streaming_transcription": "流式转写",
    "system_default": "系统默认",
    "system_prompt": "系统提示词",
    "system_prompt_help": "定义 AI 助手的角色；转写文本会作为用户消息发送。",
    "system_prompt_placeholder": "你是专业的转写修正助手。只输出修正后的文本。",
    "test": "测试",
    "text_input": "文本输入",
    "theme_accent": "主题强调色",
    "lexicon_memory": "本地词汇记忆",
    "clear_lexicon": "清空词汇记忆",
    "clear_lexicon_confirm": "删除全部已保存词汇？",
    "export_lexicon": "导出词汇记忆",
    "export_lexicon_success": "已导出 {count} 条词汇记忆到 {path}",
    "export_lexicon_failed": "词汇记忆导出失败：{reason}",
    "time_stats": "总记录: 0  总时长: 0.0 秒  成功率: 0%",
    "timeout": "超时",
    "time": "时间",
    "total_duration_format": "总时长: {duration:.1f}秒",
    "total_duration_zero": "总时长: 0.0 秒",
    "total_records_format": "总记录: {count}",
    "total_records_zero": "总记录: 0",
    "transcription": "转写",
    "transcription_path": "转写路径",
    "transcription_provider": "转写提供商",
    "transcribe_time": "转写耗时",
    "typing_delay_ms": "输入延迟 (ms)",
    "unload": "卸载",
    "use_lexicon_memory": "使用已接受的词汇记忆",
    "shortcut_count": "已绑定 {count} 个",
    "success_rate_format": "成功率: {rate:.1f}%",
    "success_rate_zero": "成功率: 0%",
}

__all__ = ["ZH_CN"]
