"""Fluent 设置界面的简体中文文案表

由 SettingsViewModelBase.translate() 在 ui.language == "zh-CN" 时查表使用。
"""

ZH_CN: dict[str, str] = {
    "ai_behavior": "AI 行为",
    "ai_processing": "AI 处理",
    "ai_provider": "AI 提供商",
    "api_key": "API 密钥",
    "api_key_optional": "API 密钥（可选）",
    "always_on_top": "始终置顶",
    "application": "应用",
    "apply": "应用",
    "audio_and_input": "音频和输入",
    "audio_device": "音频设备",
    "auto_detect_terminal": "自动检测终端应用",
    "auto_save_dragged_position": "自动保存拖动位置",
    "base_url": "基础 URL",
    "batch_reprocess": "批量重新处理",
    "revert_to_raw": "回退到原始转写",
    "chunk_duration": "分块时长",
    "clipboard_restore_delay_ms": "剪贴板恢复延迟 (ms)",
    "dashscope_default": "留空则使用 DashScope 默认地址",
    "audio_file": "音频文件",
    "close": "关闭",
    "copy_to_clipboard": "复制",
    "delete_record": "删除记录",
    "detail": "详情",
    "diagnostics": "诊断",
    "decision_reason": "决策原因",
    "enable_ai_streaming_output": "启用 AI 流式输出",
    "enable_ai_optimization": "启用 AI 文本优化",
    "enable_fallback": "启用备用输入方法",
    "enable_idle_review": "启用自动质量审查",
    "enable_itn": "启用逆文本归一化",
    "enable_sentence_split": "启用句子切分",
    "fallback": "备用输入",
    "fallback_type": "备用类型",
    "fallback_reason": "备用原因",
    "final_text": "最终文本",
    "filter_thinking_tags": "过滤思考标签",
    "history": "历史",
    "hotkey_backend": "快捷键后端",
    "hotkeys": "快捷键",
    "active_hotkeys": "当前快捷键",
    "accept": "接受",
    "add_shortcut": "添加快捷键",
    "change": "更改",
    "capture_cancel_hint": "按 Esc 取消",
    "capture_duplicate_hotkey": "该快捷键已存在",
    "capture_failed": "无法开始录制，请重试",
    "capture_idle_hint": "点击添加或更改来录制新的快捷键组合",
    "capture_ready": "准备录制快捷键",
    "capture_timed_out": "录制超时，请重试",
    "capture_unavailable": "当前环境无法录制快捷键",
    "capturing_shortcut": "正在录制快捷键",
    "at_least_one_shortcut_required": "至少需要保留一个快捷键",
    "confirm": "确认",
    "edit_shortcut": "编辑快捷键",
    "edit_hotkeys": "编辑快捷键",
    "ignore": "忽略",
    "ignore_once": "仅忽略这次",
    "always_ignore_similar": "总是忽略相似项",
    "review_ignore_scope_hint": "“仅忽略这次”只会收起当前卡片；“总是忽略相似项”会抑制后续相似建议再次进入待审查列表。",
    "language": "语言",
    "launch_at_login": "Windows 登录时启动",
    "leave_empty_default": "留空则使用默认值",
    "load": "加载",
    "load_model_on_startup": "启动时加载模型",
    "log_level": "日志级别",
    "local_sherpa": "本地 sherpa-onnx",
    "max_log_file_size": "最大日志文件大小 (MB)",
    "max_review_records": "每次审查记录数",
    "max_retries": "最大重试次数",
    "duration": "时长",
    "evidence": "证据",
    "mode": "模式",
    "model": "模型",
    "model_id": "模型 ID",
    "no_hotkeys": "未配置快捷键",
    "no_lexicon_entries": "暂无本地词汇记忆",
    "no_review_suggestions": "暂无待审查建议",
    "no_review_suggestions_in_category": "当前“{category}”下暂无待审查建议。",
    "streaming_mode": "流式模式",
    "no_history_records_loaded": "未加载历史记录",
    "openai_compatible": "OpenAI 兼容",
    "one_hotkey_per_line": "每行一个快捷键",
    "press_shortcut": "按下快捷键",
    "preferred_method": "首选方法",
    "preset_position": "预设位置",
    "provider": "提供商",
    "quality_review": "模型审查",
    "quality_review_help": "优先调用你配置的 AI 提供商生成审查建议；如果模型不可用，会退回本地安全校验。",
    "provider_credentials": "提供商凭据",
    "recording_overlay": "录音悬浮窗",
    "recording_details": "录音详情",
    "record_id": "记录 ID",
    "refresh": "刷新",
    "registered_hotkeys": "已注册快捷键",
    "remove": "移除",
    "remove_shortcut": "移除快捷键",
    "reject": "拒绝",
    "reprocess_sample": "重新处理样本",
    "review_run_completed": "模型审查完成：{records} 条记录，{suggestions} 条建议",
    "review_run_completed_empty": "模型审查完成：检查了 {records} 条记录，未发现待处理建议",
    "review_run_skipped": "审查未运行：{reason}",
    "review_categories": "审查类别",
    "review_filter_all_categories": "全部类别",
    "review_filter_show_only": "仅看此类",
    "review_filter_showing": "当前筛选",
    "review_back_to_overview": "返回总览",
    "review_group_expand": "展开",
    "review_group_collapse": "折叠",
    "review_hidden_suffix": "隐藏",
    "review_suggestion_overflow": "当前显示 {shown}/{total} 条待审查建议；系统优先展示高风险问题，其余术语候选已暂时折叠。",
    "review_suggestion_overflow_category": "当前在“{category}”中显示 {shown}/{total} 条待审查建议。",
    "review_suggestions": "审查建议",
    "review_idle_seconds": "自动审查空闲等待时间",
    "review_action_abnormal_repetition_alert": "建议检查 AI 是否卡在循环重复；这类输出通常应回退或重新处理。",
    "review_action_assistant_response_leak_alert": "建议确认 AI 是否变成了助手回复、拒绝语或占位提示；语音清理不应向用户说话。",
    "review_action_bad_ai_output_alert": "建议检查这条记录；若 AI 输出越界，应保留原始转写或重新处理。",
    "review_action_chunk_boundary_repeat_alert": "建议保留为 ASR/chunk 调试样本；若相邻片段重复，优先检查 chunk overlap 与边界去重。",
    "review_action_collapsed_to_fragment_alert": "建议优先检查是否发生极端截断；长口述若只剩一两个碎片词，通常应立即回退或重新处理。",
    "review_action_asr_failure_alert": "建议作为 ASR/fallback 调试样本保留，不会自动改变输入结果。",
    "review_action_fallback_candidate_alert": "建议保留为 fallback 条件调试样本；长录音若最终仍接近空白或噪声，说明回退条件可能还不够细。",
    "review_action_lexicon_candidate": "接受后会加入本地词汇记忆；拒绝或忽略不会影响后续输入。",
    "review_action_low_information_expansion_alert": "建议检查是否为短噪声或填充词被扩写；不会自动回写历史。",
    "review_action_over_compressed_long_input_alert": "建议检查长文本是否被总结或删减；不会自动回写历史。",
    "review_action_over_expanded_short_input_alert": "建议检查短输入是否被扩写成解释或回答；语音清理通常应保持保守。",
    "review_action_prompt_failure_pattern": "这是本地 fallback 调试线索；接受或导出都不会自动修改线上提示词。",
    "review_action_translation_command_leak_alert": "建议确认 AI 是否执行了翻译命令；语音清理不应替用户翻译。",
    "review_action_unexpected_language_shift_alert": "建议确认 AI 是否意外切换了语言；语音清理通常应保留原始语言。",
    "review_action_format_pollution_alert": "建议确认最终输入是否混入 markdown、标签或列表格式。",
    "review_debug_export_help": "可将本地 fallback 发现的失败模式导出为调试报告，不会自动改动提示词。",
    "review_debug_export_success": "已导出 {count} 条本地 fallback 调试建议到 {path}",
    "review_debug_export_failed": "调试报告导出失败：{reason}",
    "review_export_debug_report": "导出调试报告",
    "review_jobs": "最近审查运行",
    "review_job_summary": "{records} 条记录，{suggestions} 条建议",
    "review_category_boundary_violation": "边界越界",
    "review_category_boundary_violation_desc": "AI 没有停留在转写清理边界内，转而回答、翻译、切换语言或输出结构化结果。",
    "review_category_content_distortion": "内容失真",
    "review_category_content_distortion_desc": "AI 对原始内容做了过度压缩、扩写、重复或其他破坏性改动。",
    "review_category_diagnostics": "诊断样本",
    "review_category_diagnostics_desc": "主要用于 ASR 或回退链路诊断，不一定直接表示 AI 清理越界。",
    "review_category_lexicon_learning": "词汇记忆",
    "review_category_lexicon_learning_desc": "用于积累可确认的本地术语记忆，只有接受后才会生效。",
    "review_category_prompt_quality": "提示词问题",
    "review_category_prompt_quality_desc": "汇总近期反复出现的 fallback 失败模式，主要用于本地调试报告，不会自动改动线上提示词。",
    "review_priority_high": "优先处理",
    "review_priority_medium": "值得检查",
    "review_priority_low": "可稍后处理",
    "review_risk_high": "高风险",
    "review_risk_low": "低风险",
    "review_risk_medium": "中风险",
    "review_risk_high_desc": "可能已经影响最终输入质量，建议优先人工检查。",
    "review_risk_low_desc": "主要用于诊断或样本积累，通常不直接改变输入行为。",
    "review_risk_medium_desc": "可能改善后续纠错，但需要用户确认后才会生效。",
    "review_type_abnormal_repetition_alert": "异常重复警报",
    "review_type_assistant_response_leak_alert": "助手回复泄漏警报",
    "review_type_asr_failure_alert": "ASR 失败样本",
    "review_type_bad_ai_output_alert": "AI 越界警报",
    "review_type_chunk_boundary_repeat_alert": "分块边界重复",
    "review_type_collapsed_to_fragment_alert": "极端碎片化压缩",
    "review_type_fallback_candidate_alert": "Fallback 候选样本",
    "review_type_lexicon_candidate": "术语候选",
    "review_type_low_information_expansion_alert": "低信息扩写",
    "review_type_over_compressed_long_input_alert": "长文本压缩警报",
    "review_type_over_expanded_short_input_alert": "短输入扩写警报",
    "review_type_prompt_failure_pattern": "提示词失败模式",
    "review_type_translation_command_leak_alert": "翻译越界警报",
    "review_type_unexpected_language_shift_alert": "语言漂移警报",
    "review_type_format_pollution_alert": "格式污染警报",
    "local_example": "本地示例",
    "local_examples": "本地示例",
    "local_examples_more": "（另 {count} 条）",
    "run_review_now": "立即运行模型审查",
    "source_records": "来源记录",
    "reprocess_of": "重处理来源",
    "revert": "还原",
    "retry": "重试",
    "search_history": "搜索转写或 AI 文本",
    "seconds": "秒",
    "selected_hotkey": "已选快捷键",
    "show_console_output": "显示控制台输出",
    "show_recording_overlay": "显示录音悬浮窗",
    "show_tray_notifications": "显示托盘通知",
    "start_minimized": "启动后最小化到托盘",
    "start_ai_after_first_chunk": "首个 ASR 分块完成后启动 AI",
    "streaming_transcription": "流式转写",
    "system_default": "系统默认",
    "system_prompt": "系统提示词",
    "system_prompt_help": "定义 AI 助手的角色；转写文本会作为用户消息发送。",
    "system_prompt_placeholder": "你是专业的转写修正助手。只输出修正后的文本。",
    "test": "测试",
    "text_input": "文本输入",
    "theme_accent": "主题强调色",
    "lexicon_memory": "本地词汇记忆",
    "clear_lexicon": "清空词汇记忆",
    "clear_learning_data": "清空学习数据",
    "clear_learning_data_success": "已清空本地学习数据。",
    "clear_learning_data_failed": "清空本地学习数据失败。",
    "export_lexicon": "导出词汇记忆",
    "export_lexicon_success": "已导出 {count} 条词汇记忆到 {path}",
    "export_lexicon_failed": "词汇记忆导出失败：{reason}",
    "open_source_record": "打开来源记录",
    "open_example_record": "打开示例记录",
    "time_stats": "总记录: 0  总时长: 0.0 秒  成功率: 0%",
    "timeout": "超时",
    "time": "时间",
    "total_duration_format": "总时长: {duration:.1f}秒",
    "total_duration_zero": "总时长: 0.0 秒",
    "total_records_format": "总记录: {count}",
    "total_records_zero": "总记录: 0",
    "transcription": "转写",
    "transcription_path": "转写路径",
    "transcription_provider": "转写提供商",
    "transcribe_time": "转写耗时",
    "typing_delay_ms": "输入延迟 (ms)",
    "unload": "卸载",
    "use_lexicon_memory": "使用已接受的词汇记忆",
    "shortcut_count": "已绑定 {count} 个",
    "success_rate_format": "成功率: {rate:.1f}%",
    "success_rate_zero": "成功率: 0%",
}

__all__ = ["ZH_CN"]
